---
# configure deployment and continuous integration at travis-ci.com

arch: amd64
dist: bionic
language: cpp
os: linux

jobs:
  include:

    # MacOSX32 and MacOSX64 (job .1):
    - os: osx
      osx_image: xcode9.4.1
      script:
        - date
        - ./gradlew build --console=plain --no-daemon -Ptravis=osx_intel

    # Linux32 and Linux64 non-multithreaded (job .2):
    - env:
        - FLAVOR=noMt
      addons:
        apt:
          packages:
            - g++-7-multilib
      script:
        - date
        - sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/asm
        - sudo ln -s /usr/include/x86_64-linux-gnu/bits /usr/include/bits
        - g++ --version
        - ./gradlew build --console=plain --no-daemon -Ptravis=amd64

    # Linux64 multithreaded (job .3):
    - env:
        - FLAVOR=Mt64
      script:
        - date
        - g++ --version
        - ./gradlew build --console=plain --no-daemon -Ptravis=amd64mt

    # Linux_ARM32 software floating-point (job .4):
    - arch: arm64
      compiler: arm-linux-gnueabi-g++-7
      addons:
        apt:
          packages:
            - g++-7-arm-linux-gnueabi
      env:
        - FLAVOR=Arm32
      script:
        - date
        - arm-linux-gnueabi-g++-7 -E -v
        - travis_wait 20 ./gradlew assemble --console=plain --no-daemon -Ptravis=arm32

    # Linux_ARM32hf (job .5):
    - arch: arm64
      compiler: arm-linux-gnueabihf-g++-6
      addons:
        apt:
          packages:
            - g++-6-arm-linux-gnueabihf
      env:
        - FLAVOR=Arm32hf
      script:
        - date
        - arm-linux-gnueabihf-g++-6 -E -v
        - travis_wait 20 ./gradlew assemble --console=plain --no-daemon -Ptravis=arm32hf

    # Linux_ARM64 double-precision (job .6):
    - arch: arm64
      compiler: gcc-6
      addons:
        apt:
          packages:
            - g++-6
      env:
        - FLAVOR=Dp64
      script:
        - date
        - aarch64-linux-gnu-g++-6 -E -v
        - travis_wait 20 ./gradlew build --exclude-task check --console=plain --no-daemon -Pflavor=Dp -Ptravis=arm64

    # Linux_ARM64 single-precision (job .7):
    - arch: arm64
      compiler: gcc-6
      addons:
        apt:
          packages:
            - g++-6
      env:
        - FLAVOR=Sp64
      script:
        - date
        - aarch64-linux-gnu-g++-6 -E -v
        - travis_wait 20 ./gradlew build --console=plain --no-daemon -Pflavor=Sp -Ptravis=arm64

    # Android_ARM7, Android_ARM8, Android_X86, and Android_X86_64 (job .8):
    - dist: trusty
      language: android
      android:
        components:
          - tools
      script:
        - date
        - sdkmanager --list
        - echo y | sdkmanager "ndk;21.3.6528147" > /dev/null
        - ./gradlew copyToDist --build-file=android.gradle --console=plain --no-daemon

    # MacOSX_ARM64 (job .9):
    - os: osx
      osx_image: xcode14.2
      script:
        - date
        - ./gradlew assemble --console=plain --no-daemon -Ptravis=osx_arm


addons:
  apt:
    update: true
after_failure:
  - cat build/reports/tests/test/classes/TestLibbulletjme.html
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

# Deploy using personal access token expiring on Sep 16 2023
# Browse to GitHub user pulldown -> Settings -> "Developer settings"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "lXM28894Og58sDgKKg40L8N5nH8saXUdeo/w+eV2ntcwgvVFK/bp4nlfBcYb2oRdcV1V2mF9nRFGT4pUY6ptymH6P/fwqW+OuoL2k65zipHK2FLPKywV7ayw5h9KzWidLuwxq0poMzfUIFfneCL4PF1wH0NKDdKx8hDGDgcdHuLHQit9eSqKYGuKGJ887hdmoyKgsSafSxE/2YkOZ7uvj5q9TjNknaFPGiAyhbo59Ty0hsct1jb8gGvEAbtMhuFEkUpwjAsyB2s+YuFA+d3ENcPS8IVh0IncJZM7353W8n2uBRWJwnDsBVuLcEmZHeG1zllg475Ht1zoBw2jR+XOwHJWL9uW+q4voRYMsWk9wWqDqRE0igqyhok15RLsyFRrujyDx3zN9vbrepXqbVVv2pGpPhsZcFOBlCf9RdzAprIt/7EmxGSXzMx118GirYeT8WoJ7m83/QtI4i8rbMfXc0hjkpupL0s0RT04yr4/0GrMpyyR+jca+bgu1CaoncUYzk3bN0SXGEKZU+2smbu5vgBDBuXsd6PPp5OXUAoWukZzYd2mUumJWgaxCVY9dx4dArKf4HFJ8q0OEBB0QTy8ecozW6WEVa1jOkvB6X+/oxBPFLtxIpUOkT1Z9Op4eh+IBaDag4ybqOKklBP4GSMPouiCB0CNRLK+HswrnctcVwE="
  file:
    - dist/Android_ARM7DebugSp_libbulletjme.so
    - dist/Android_ARM7ReleaseSp_libbulletjme.so
    - dist/Android_ARM8DebugSp_libbulletjme.so
    - dist/Android_ARM8ReleaseSp_libbulletjme.so
    - dist/Android_X86DebugSp_libbulletjme.so
    - dist/Android_X86ReleaseSp_libbulletjme.so
    - dist/Android_X86_64DebugSp_libbulletjme.so
    - dist/Android_X86_64ReleaseSp_libbulletjme.so
    - dist/Linux32DebugDp_libbulletjme.so
    - dist/Linux32DebugSp_libbulletjme.so
    - dist/Linux32ReleaseDp_libbulletjme.so
    - dist/Linux32ReleaseSp_libbulletjme.so
    - dist/Linux64DebugDp_libbulletjme.so
    - dist/Linux64DebugDpMt_libbulletjme.so
    - dist/Linux64DebugSp_libbulletjme.so
    - dist/Linux64DebugSpMt_libbulletjme.so
    - dist/Linux64ReleaseDp_libbulletjme.so
    - dist/Linux64ReleaseDpMt_libbulletjme.so
    - dist/Linux64ReleaseSp_libbulletjme.so
    - dist/Linux64ReleaseSpMt_libbulletjme.so
    - dist/Linux_ARM32DebugDp_libbulletjme.so
    - dist/Linux_ARM32DebugSp_libbulletjme.so
    - dist/Linux_ARM32ReleaseDp_libbulletjme.so
    - dist/Linux_ARM32ReleaseSp_libbulletjme.so
    - dist/Linux_ARM32hfDebugDp_libbulletjme.so
    - dist/Linux_ARM32hfDebugSp_libbulletjme.so
    - dist/Linux_ARM32hfReleaseDp_libbulletjme.so
    - dist/Linux_ARM32hfReleaseSp_libbulletjme.so
    - dist/Linux_ARM64DebugDp_libbulletjme.so
    - dist/Linux_ARM64DebugSp_libbulletjme.so
    - dist/Linux_ARM64ReleaseDp_libbulletjme.so
    - dist/Linux_ARM64ReleaseSp_libbulletjme.so
    - dist/MacOSX32DebugDp_libbulletjme.dylib
    - dist/MacOSX32DebugSp_libbulletjme.dylib
    - dist/MacOSX32ReleaseDp_libbulletjme.dylib
    - dist/MacOSX32ReleaseSp_libbulletjme.dylib
    - dist/MacOSX64DebugDp_libbulletjme.dylib
    - dist/MacOSX64DebugSp_libbulletjme.dylib
    - dist/MacOSX64ReleaseDp_libbulletjme.dylib
    - dist/MacOSX64ReleaseSp_libbulletjme.dylib
    - dist/MacOSX_ARM64DebugDp_libbulletjme.dylib
    - dist/MacOSX_ARM64DebugSp_libbulletjme.dylib
    - dist/MacOSX_ARM64ReleaseDp_libbulletjme.dylib
    - dist/MacOSX_ARM64ReleaseSp_libbulletjme.dylib
  on:
    repo: stephengold/Libbulletjme
    tags: true   # deploy on tag push only
