language: cpp

matrix:
  include:
  - os: osx
    osx_image: xcode9.3
    script:
    - ./gradlew build --console=plain --no-daemon -Ptravis=osx
  - os: linux
    arch: amd64
    compiler: gcc
    addons:
      apt:
        packages:
        - g++-multilib
        update: true
    script:
    - ./gradlew build --console=plain --no-daemon -Ptravis=amd64
  - os: linux
    arch: arm64
    compiler: gcc
    addons:
      apt:
        packages:
        - default-jre
        - g++
        update: true
    script:
    - ./gradlew build --console=plain --no-daemon -Ptravis=arm64

after_failure:
 - cat build/reports/tests/test/classes/TestLibbulletjme.html

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ObhRzkbGix4/iAgZZDhmdeuFZ/VNwHnkWRSPiZRKq+lzSNSU7EOsCSTV5eDun0ugC
  file:
  - dist/Linux32DebugDp_libbulletjme.so
  - dist/Linux32DebugSp_libbulletjme.so
  - dist/Linux64DebugDp_libbulletjme.so
  - dist/Linux64DebugSp_libbulletjme.so
  - dist/Linux32ReleaseDp_libbulletjme.so
  - dist/Linux32ReleaseSp_libbulletjme.so
  - dist/Linux64ReleaseDp_libbulletjme.so
  - dist/Linux64ReleaseSp_libbulletjme.so
  - dist/Linux_ARM64DebugDp_libbulletjme.so
  - dist/Linux_ARM64DebugSp_libbulletjme.so
  - dist/Linux_ARM64ReleaseDp_libbulletjme.so
  - dist/Linux_ARM64ReleaseSp_libbulletjme.so
  - dist/MacOSX32DebugDp_libbulletjme.dylib
  - dist/MacOSX32DebugSp_libbulletjme.dylib
  - dist/MacOSX64DebugDp_libbulletjme.dylib
  - dist/MacOSX64DebugSp_libbulletjme.dylib
  - dist/MacOSX32ReleaseDp_libbulletjme.dylib
  - dist/MacOSX32ReleaseSp_libbulletjme.dylib
  - dist/MacOSX64ReleaseDp_libbulletjme.dylib
  - dist/MacOSX64ReleaseSp_libbulletjme.dylib
  on:
    repo: stephengold/Libbulletjme
    tags: true   # deploy on tag push only
