---
# configure deployment and continuous integration at travis-ci.com

arch: amd64
dist: xenial
language: cpp
os: linux

jobs:
  include:
    - os: osx
      osx_image: xcode9.4.1
      script:
        - ./gradlew build --console=plain --no-daemon -Ptravis=osx
    - dist: trusty
      compiler: gcc-4.7
      addons:
        apt:
          packages:
            - g++-4.7-multilib
      script:
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 90
        - sudo ln -s /usr/include/x86_64-linux-gnu/asm /usr/include/asm
        - g++ --version
        - ./gradlew build --console=plain --no-daemon -Ptravis=amd64
    - compiler: gcc-5
      script:
        - g++ --version
        - ./gradlew build --console=plain --no-daemon -Ptravis=amd64mt
    - arch: arm64
      compiler: arm-linux-gnueabi-g++-5
      addons:
        apt:
          packages:
            - g++-5-arm-linux-gnueabi
      env:
        - FLAVOR=Dp32
      script:
        - arm-linux-gnueabi-g++-5 -E -v
        - travis_wait 20 ./gradlew assemble --console=plain --no-daemon -Pflavor=Dp -Ptravis=arm32
    - arch: arm64
      compiler: arm-linux-gnueabi-g++-5
      addons:
        apt:
          packages:
            - g++-5-arm-linux-gnueabi
      env:
        - FLAVOR=Sp32
      script:
        - arm-linux-gnueabi-g++-5 -E -v
        - travis_wait 20 ./gradlew assemble --console=plain --no-daemon -Pflavor=Sp -Ptravis=arm32
    - arch: arm64
      compiler: arm-linux-gnueabihf-g++-5
      addons:
        apt:
          packages:
            - g++-5-arm-linux-gnueabihf
      env:
        - FLAVOR=Dp32
      script:
        - arm-linux-gnueabihf-g++-5 -E -v
        - travis_wait 20 ./gradlew assemble --console=plain --no-daemon -Pflavor=Dp -Ptravis=arm32hf
    - arch: arm64
      compiler: arm-linux-gnueabihf-g++-5
      addons:
        apt:
          packages:
            - g++-5-arm-linux-gnueabihf
      env:
        - FLAVOR=Sp32
      script:
        - arm-linux-gnueabihf-g++-5 -E -v
        - travis_wait 20 ./gradlew assemble --console=plain --no-daemon -Pflavor=Sp -Ptravis=arm32hf
    - arch: arm64
      compiler: gcc
      env:
        - FLAVOR=Dp64
      script:
        - travis_wait 20 ./gradlew build --console=plain --no-daemon -Pflavor=Dp -Ptravis=arm64
    - arch: arm64
      compiler: gcc
      env:
        - FLAVOR=Sp64
      script:
        - travis_wait 20 ./gradlew build --console=plain --no-daemon -Pflavor=Sp -Ptravis=arm64
    - dist: trusty
      language: android
      android:
        components:
          - tools
      script:
        - echo y | sdkmanager "ndk;21.3.6528147" > /dev/null
        - echo y | sdkmanager "patcher;v4" > /dev/null
        - ./gradlew copyToDist --build-file=android.gradle --console=plain --no-daemon


addons:
  apt:
    update: true
after_failure:
  - cat build/reports/tests/test/classes/TestLibbulletjme.html
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "NOm6vmrMzDP1noo50/j3zHQ2ZDmAD7qeDOzCoNE6khQdscIHI6KU1CvRrU5FcDSj8pgOYECTAWrbaXPDTjwusJy9BDHUT75OYYGsehdLQkKgHJob5h57jLS0LCiAQ/uq25qCVeo1UScQfhq4hZsKJgydBcodhU8uiAbE5DvvJCgigqhATXf4tmBr8+TGhdXsaCxVPtVWgr83EDeIKVDDoWWqGiSBOMWwUQt552JyDu32EyOmK+BsH9OVRqjGunBrRjR4XdfAUF1Y12dIIODDfCv6rPod5jWsgmX8uNSFqIIZnT6nFxaQ2vGow37YX/7/jr/ASyr8eU7G0xHkMvgPnQR1sEUDfs0BcxLL0OCA68BsDhWO8f2WcInAYMR+8ixFhF8W38voqDcmhUDJ6W3Fl8I27rOX3J+OujBS+QxT+wITpHVoWxmH2aW6E1xK9jCMAb9c/knYbUysOS4rDLL/uBtvQv4eNAdZD+Ad0c0rsTsntUhLWtPhUMGE9uJBV8UAmDrtvf30mClGEIzbuVhiTGv/YJ3sLVaoiElklLdKFW1hkSDyOPggWFwb9AX6fng9Bre43OKQ0IJBm+LRGWOd5E6xaeqm7nznkGBN+8kDN5lvz+/Js5sZB7TSIaNqn0nVB1AZqb2M794YOGlFiDkzaj/vcEc0wbfoQQ7Tpu3XR+M="
  file:
    - dist/Android_ARM7DebugSp_libbulletjme.so
    - dist/Android_ARM7ReleaseSp_libbulletjme.so
    - dist/Android_ARM8DebugSp_libbulletjme.so
    - dist/Android_ARM8ReleaseSp_libbulletjme.so
    - dist/Android_X86DebugSp_libbulletjme.so
    - dist/Android_X86ReleaseSp_libbulletjme.so
    - dist/Android_X86_64DebugSp_libbulletjme.so
    - dist/Android_X86_64ReleaseSp_libbulletjme.so
    - dist/Linux32DebugDp_libbulletjme.so
    - dist/Linux32DebugSp_libbulletjme.so
    - dist/Linux32ReleaseDp_libbulletjme.so
    - dist/Linux32ReleaseSp_libbulletjme.so
    - dist/Linux64DebugDp_libbulletjme.so
    - dist/Linux64DebugDpMt_libbulletjme.so
    - dist/Linux64DebugSp_libbulletjme.so
    - dist/Linux64DebugSpMt_libbulletjme.so
    - dist/Linux64ReleaseDp_libbulletjme.so
    - dist/Linux64ReleaseDpMt_libbulletjme.so
    - dist/Linux64ReleaseSp_libbulletjme.so
    - dist/Linux64ReleaseSpMt_libbulletjme.so
    - dist/Linux_ARM32DebugDp_libbulletjme.so
    - dist/Linux_ARM32DebugSp_libbulletjme.so
    - dist/Linux_ARM32ReleaseDp_libbulletjme.so
    - dist/Linux_ARM32ReleaseSp_libbulletjme.so
    - dist/Linux_ARM32hfDebugDp_libbulletjme.so
    - dist/Linux_ARM32hfDebugSp_libbulletjme.so
    - dist/Linux_ARM32hfReleaseDp_libbulletjme.so
    - dist/Linux_ARM32hfReleaseSp_libbulletjme.so
    - dist/Linux_ARM64DebugDp_libbulletjme.so
    - dist/Linux_ARM64DebugSp_libbulletjme.so
    - dist/Linux_ARM64ReleaseDp_libbulletjme.so
    - dist/Linux_ARM64ReleaseSp_libbulletjme.so
    - dist/MacOSX32DebugDp_libbulletjme.dylib
    - dist/MacOSX32DebugSp_libbulletjme.dylib
    - dist/MacOSX32ReleaseDp_libbulletjme.dylib
    - dist/MacOSX32ReleaseSp_libbulletjme.dylib
    - dist/MacOSX64DebugDp_libbulletjme.dylib
    - dist/MacOSX64DebugSp_libbulletjme.dylib
    - dist/MacOSX64ReleaseDp_libbulletjme.dylib
    - dist/MacOSX64ReleaseSp_libbulletjme.dylib
  on:
    repo: stephengold/Libbulletjme
    tags: true   # deploy on tag push only
