language: cpp

compiler: gcc

matrix:
  include:
  - os: osx
    osx_image: xcode9.3
  - os: linux
    jdk: oraclejdk8

addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib

script:
- ./gradlew build --console=plain --no-daemon

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ObhRzkbGix4/iAgZZDhmdeuFZ/VNwHnkWRSPiZRKq+lzSNSU7EOsCSTV5eDun0ugCxV9O0LKnYdzZBFM5SwfNEIGmj1Frp4Cs7m1iSlxhL7wEv3N6rBtS+P166Fwf6XRxvtC6r54szRXwg2oD9tJ9urtm/xAwGZCVWr0M11A2/D3kIhtawVvw4a5fTg8NRwtb/8e8bfDyPddUmbElPH52539vA6CPawoXW5CHWcWZsY+sIRtkJOjJv4cK9GNBylmYmaEW74AjYL+t46U8qiMZo8Yyb/VQDgZ/xkGwnwEWWp4aROlj6NK/ICsrDZGrr8+dVIHbZ3QXpaJ0VoWB4oXDP0zFY5a8KpMFdWycu1xd2SMCzs5na4jfJHyblHJwhKpBfcW5079p4jx7n2OpCJHFxFY94HUo5HhqBRUr6QHwrM901PO/FtxF4ZmuMbGE8MfSIpmCASnl4fyh/Vp6qPrALVefId6Pub6QOuXWBDM3FKRuVAABYu5h6OX2Nwres6gWe42QkQ9On+5AGkfrw/OPw/e7ax/vmdqI89BkAD3zMLJ4SQeVcZdNtiyWDp5drRGsaXLS6lOoz8BuP6tEkOAdNhwtt9lxb9WU1XXrrmHGTvLnONZoyFg7b0eiB+/mLNDbB5I9oatPGbplCxtJF1CoNWRFJNfSJqmg31ekBSyHYc=
  file:
  - dist/Linux32DebugDp_libbulletjme.so
  - dist/Linux32DebugSp_libbulletjme.so
  - dist/Linux64DebugDp_libbulletjme.so
  - dist/Linux64DebugSp_libbulletjme.so
  - dist/Linux32ReleaseDp_libbulletjme.so
  - dist/Linux32ReleaseSp_libbulletjme.so
  - dist/Linux64ReleaseDp_libbulletjme.so
  - dist/Linux64ReleaseSp_libbulletjme.so
  - dist/MacOSX32DebugDp_libbulletjme.dylib
  - dist/MacOSX32DebugSp_libbulletjme.dylib
  - dist/MacOSX64DebugDp_libbulletjme.dylib
  - dist/MacOSX64DebugSp_libbulletjme.dylib
  - dist/MacOSX32ReleaseDp_libbulletjme.dylib
  - dist/MacOSX32ReleaseSp_libbulletjme.dylib
  - dist/MacOSX64ReleaseDp_libbulletjme.dylib
  - dist/MacOSX64ReleaseSp_libbulletjme.dylib
  on:
    repo: stephengold/Libbulletjme
    tags: true   # deploy on tag push only
