/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_collision_shapes_SimplexCollisionShape */

#ifndef _Included_com_jme3_bullet_collision_shapes_SimplexCollisionShape
#define _Included_com_jme3_bullet_collision_shapes_SimplexCollisionShape
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jme3_bullet_collision_shapes_SimplexCollisionShape_numAxes
#define com_jme3_bullet_collision_shapes_SimplexCollisionShape_numAxes 3L
/*
 * Class:     com_jme3_bullet_collision_shapes_SimplexCollisionShape
 * Method:    createShape
 * Signature: (Lorg/joml/Vector3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_SimplexCollisionShape_createShape__Lorg_joml_Vector3f_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_jme3_bullet_collision_shapes_SimplexCollisionShape
 * Method:    createShape
 * Signature: (Lorg/joml/Vector3f;Lorg/joml/Vector3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_SimplexCollisionShape_createShape__Lorg_joml_Vector3f_2Lorg_joml_Vector3f_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_jme3_bullet_collision_shapes_SimplexCollisionShape
 * Method:    createShape
 * Signature: (Lorg/joml/Vector3f;Lorg/joml/Vector3f;Lorg/joml/Vector3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_SimplexCollisionShape_createShape__Lorg_joml_Vector3f_2Lorg_joml_Vector3f_2Lorg_joml_Vector3f_2
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_jme3_bullet_collision_shapes_SimplexCollisionShape
 * Method:    createShape
 * Signature: (Lorg/joml/Vector3f;Lorg/joml/Vector3f;Lorg/joml/Vector3f;Lorg/joml/Vector3f;)J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_collision_shapes_SimplexCollisionShape_createShape__Lorg_joml_Vector3f_2Lorg_joml_Vector3f_2Lorg_joml_Vector3f_2Lorg_joml_Vector3f_2
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     com_jme3_bullet_collision_shapes_SimplexCollisionShape
 * Method:    recalcAabb
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_collision_shapes_SimplexCollisionShape_recalcAabb
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
