/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jme3_bullet_objects_infos_RigidBodyMotionState */

#ifndef _Included_com_jme3_bullet_objects_infos_RigidBodyMotionState
#define _Included_com_jme3_bullet_objects_infos_RigidBodyMotionState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jme3_bullet_objects_infos_RigidBodyMotionState
 * Method:    applyTransform
 * Signature: (JLorg/joml/Vector3f;Lorg/joml/Quaternionf;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jme3_bullet_objects_infos_RigidBodyMotionState_applyTransform
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_RigidBodyMotionState
 * Method:    createMotionState
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jme3_bullet_objects_infos_RigidBodyMotionState_createMotionState
  (JNIEnv *, jclass);

/*
 * Class:     com_jme3_bullet_objects_infos_RigidBodyMotionState
 * Method:    finalizeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_RigidBodyMotionState_finalizeNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jme3_bullet_objects_infos_RigidBodyMotionState
 * Method:    getWorldLocation
 * Signature: (JLorg/joml/Vector3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_RigidBodyMotionState_getWorldLocation
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_RigidBodyMotionState
 * Method:    getWorldLocationDp
 * Signature: (JLorg/joml/Vector3d;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_RigidBodyMotionState_getWorldLocationDp
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_RigidBodyMotionState
 * Method:    getWorldRotation
 * Signature: (JLorg/joml/Matrix3f;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_RigidBodyMotionState_getWorldRotation
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_RigidBodyMotionState
 * Method:    getWorldRotationDp
 * Signature: (JLorg/joml/Matrix3d;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_RigidBodyMotionState_getWorldRotationDp
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_RigidBodyMotionState
 * Method:    getWorldRotationQuat
 * Signature: (JLorg/joml/Quaternionf;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_RigidBodyMotionState_getWorldRotationQuat
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_jme3_bullet_objects_infos_RigidBodyMotionState
 * Method:    getWorldRotationQuatDp
 * Signature: (JLorg/joml/Quaterniond;)V
 */
JNIEXPORT void JNICALL Java_com_jme3_bullet_objects_infos_RigidBodyMotionState_getWorldRotationQuatDp
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
