name: continuous integration workflow for GitHub Actions
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: sudo apt-get install -y g++-multilib 
    - run: ./gradlew build --console=plain --no-daemon
